/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.GUI;

import com.mycompany.proyectofinal.Controladora;
import com.mycompany.GUI.Button;
import com.mycompany.GUI.TitlePanel;
import com.mycompany.GUI.Tabla;
import com.mycompany.proyectofinal.Caja;
import com.mycompany.proyectofinal.Cliente;
import com.mycompany.proyectofinal.Producto;
import com.mycompany.proyectofinal.Proveedor;
import com.mycompany.proyectofinal.Servicio;
import com.mycompany.proyectofinal.Turno;
import com.mycompany.proyectofinal.Usuario;

import java.io.File;
import java.io.IOException;
import javax.swing.GroupLayout.*;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.border.EmptyBorder;
import javax.swing.table.*;
import java.util.List;


public class Login extends javax.swing.JFrame {
    
    CardLayout card;
    Controladora control;
    
    private Tabla tablaClientes2;
    private Tabla tablaTurnos;
    private DefaultTableModel modeloClientes2;
    private DefaultTableModel modeloTurnos;
    private Tabla tablaEmpleados;
    private DefaultTableModel modeloEmpleados;
    private Tabla tablaServicios;
    private DefaultTableModel modeloServicios;
    private Tabla tablaProductos;
    private DefaultTableModel modeloProductos;
    private Tabla tablaProveedores;
    private DefaultTableModel modeloProveedores;
    private Tabla tablaCaja;
    private DefaultTableModel modeloCaja;
    
    /**
     * Creates new form Ventana
     */
    
    
    
    public Login() {
        initComponents();
        this.setVisible(true);
        this.setTitle("HY Peluquería");
        this.setSize(900,600);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        card = (CardLayout) mainPanel.getLayout();
        
        SwingUtilities.invokeLater(() -> {
            mainPanel.requestFocusInWindow();
        });
        
        
        
        
        
        
        control = new Controladora();
        
        
        
        card.show(mainPanel, "LoginForm");
        //card.show(mainPanel, "mainScreen");
        
        

        btnLogin1.setBackground(Styles.accentDark);
        btnLogin1.setContentAreaFilled(false);
        btnLogin1.setBorderPainted(false);
        btnLogin1.setOpaque(true);
        
        ButtonSec btnRegister = new ButtonSec("Registrarse");
        jPanel3.add(btnRegister);
        
        btnRegister.setBounds(53, jPanel3.getHeight() - 130, 150, 30);
        btnRegister.setSize(251,30);
        
        btnRegister.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Code to execute when the button is clicked
                System.out.println("Logout button clicked");
                AltaEmpleados form = new AltaEmpleados();
                 form.addWindowListener(new WindowAdapter() {
                        @Override
                        public void windowClosed(WindowEvent e) {
                            Login newLog = new Login();
                            newLog.setVisible(true);
                            newLog.setLocationRelativeTo(null);
                        }
                    });
                form.setVisible(true);
                form.setLocationRelativeTo(null);
                dispose();
            }
        });
        
        
        setupLoginPanel();
        
        JCheckBox check = new JCheckBox("Mostrar Contraseña");
        jPanel3.add(check);
        
        check.setBounds(180, jPanel3.getHeight() - 220, 150, 30);
        check.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                 if (check.isSelected()){
                    txtPassword2.setEchoChar((char) 0);
                }else{
                    txtPassword2.setEchoChar('*');
                }
            }
        });
        jPanel3.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                btnRegister.setBounds(53, jPanel3.getHeight() - 130, 150, 30);
                btnRegister.setSize(251,30);
                
                check.setBounds(180, jPanel3.getHeight() - 220, 150, 30);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        LoginForm = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnLogin1 = new javax.swing.JButton();
        txtUser1 = new javax.swing.JTextField();
        lblUser1 = new javax.swing.JLabel();
        lblPass1 = new javax.swing.JLabel();
        txtPassword2 = new javax.swing.JPasswordField();
        lblLogin1 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mainPanel.setLayout(new java.awt.CardLayout());

        LoginForm.setBackground(new java.awt.Color(243, 239, 215));
        LoginForm.setPreferredSize(new java.awt.Dimension(800, 500));
        LoginForm.setVerifyInputWhenFocusTarget(false);

        jPanel3.setBackground(new java.awt.Color(250, 250, 250));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(238, 238, 238)));
        jPanel3.setName("jPanel2"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 400));

        btnLogin1.setBackground(new java.awt.Color(149, 90, 207));
        btnLogin1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogin1.setForeground(new java.awt.Color(251, 251, 251));
        btnLogin1.setText("Iniciar Sesión");
        btnLogin1.setFocusPainted(false);
        btnLogin1.setName("btnLogin"); // NOI18N
        btnLogin1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnLogin1FocusGained(evt);
            }
        });
        btnLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLogin1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLogin1MouseExited(evt);
            }
        });
        btnLogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin1ActionPerformed(evt);
            }
        });

        txtUser1.setBackground(new java.awt.Color(229, 229, 229));
        txtUser1.setForeground(new java.awt.Color(153, 153, 153));
        txtUser1.setText("Ingrese su nombre de usuario");
        txtUser1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUser1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtUser1FocusLost(evt);
            }
        });

        lblUser1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblUser1.setForeground(new java.awt.Color(91, 91, 91));
        lblUser1.setText("Nombre de Usuario");

        lblPass1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPass1.setForeground(new java.awt.Color(93, 93, 93));
        lblPass1.setText("Contraseña");

        txtPassword2.setBackground(new java.awt.Color(229, 229, 229));
        txtPassword2.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword2.setText("contraseña");
        txtPassword2.setName(""); // NOI18N
        txtPassword2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPassword2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPassword2FocusLost(evt);
            }
        });

        lblLogin1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblLogin1.setForeground(new java.awt.Color(51, 51, 51));
        lblLogin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogin1.setText("Iniciar Sesión");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPassword2)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUser1)
                        .addComponent(lblPass1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblLogin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogin1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblUser1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblPass1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btnLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane2.setBackground(new java.awt.Color(255, 204, 204));
        jLayeredPane2.setPreferredSize(new java.awt.Dimension(500, 400));

        jLabel3.setBackground(new java.awt.Color(255, 204, 204));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/7020304.jpg"))); // NOI18N
        jLabel3.setText("jLabel2");
        jLabel3.setPreferredSize(new java.awt.Dimension(500, 400));

        jLayeredPane2.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout LoginFormLayout = new javax.swing.GroupLayout(LoginForm);
        LoginForm.setLayout(LoginFormLayout);
        LoginFormLayout.setHorizontalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginFormLayout.createSequentialGroup()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        LoginFormLayout.setVerticalGroup(
            LoginFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
            .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 574, Short.MAX_VALUE)
        );

        mainPanel.add(LoginForm, "login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
    private void btnLogin1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogin1MouseEntered
        btnLogin1.setBackground(Styles.accentLightHover);
    }//GEN-LAST:event_btnLogin1MouseEntered

    private void btnLogin1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogin1MouseExited
        btnLogin1.setBackground(Styles.accentDark);
    }//GEN-LAST:event_btnLogin1MouseExited
/*LOGICA
    DE LOGIN*/
    private void btnLogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin1ActionPerformed
        btnLogin1.setFocusPainted(false); // Remove the focus border
        btnLogin1.setBorder(BorderFactory.createEmptyBorder()); // Remove any border

        String user = txtUser1.getText();
        String pass = txtPassword2.getText();

        int userId = control.validarUsuario2(user, pass);

        if (userId != -1) {
            control.setLoggedInUserId(userId); // Store the logged-in user ID
            //store the current users role
            String role = control.getUserRole(userId); // Retrieve and store user role
            control.setLoggedInUserRole(role);
            
            System.out.println(role);
            System.out.println(userId);

            // Switch to the main screen
            Ventana form = new Ventana(role, userId);
            form.setVisible(true);
            dispose();
            form.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(null, "Usuario o contraseña incorrectos.", "Login", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnLogin1ActionPerformed

    private void txtUser1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUser1FocusGained
        if(txtUser1.getText().equals("Ingrese su nombre de usuario")){
            txtUser1.setText("");
            txtUser1.setForeground(Styles.fontDark);
        }
        
    }//GEN-LAST:event_txtUser1FocusGained

    private void txtUser1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUser1FocusLost
       if (txtUser1.getText().isEmpty()){
           txtUser1.setText("Ingrese su nombre de usuario");
           txtUser1.setForeground(Styles.fontGreyDark);
       }
    }//GEN-LAST:event_txtUser1FocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        //
    }//GEN-LAST:event_formWindowOpened

    private void txtPassword2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassword2FocusGained
        if(txtPassword2.getText().equals("contraseña")){
            txtPassword2.setText("");
            txtPassword2.setForeground(Styles.fontDark);
        }
    }//GEN-LAST:event_txtPassword2FocusGained

    private void txtPassword2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPassword2FocusLost
        if (txtPassword2.getText().isEmpty()){
           txtPassword2.setText("contraseña");
           txtPassword2.setForeground(Styles.fontGreyLight);
       }
    }//GEN-LAST:event_txtPassword2FocusLost

    private void btnLogin1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnLogin1FocusGained
        btnLogin1.setFocusPainted(false); // Remove the focus border
        btnLogin1.setBorder(BorderFactory.createEmptyBorder()); // Remove any border

    }//GEN-LAST:event_btnLogin1FocusGained
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginForm;
    private javax.swing.JButton btnLogin1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblLogin1;
    private javax.swing.JLabel lblPass1;
    private javax.swing.JLabel lblUser1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPasswordField txtPassword2;
    private javax.swing.JTextField txtUser1;
    // End of variables declaration//GEN-END:variables

    
    //UI
    public void panelSetup(String titulo, JPanel card){
        //titulo, panel norte
        TitlePanel title = new TitlePanel(titulo);
        card.add(title, BorderLayout.NORTH);
        
        //panel para la tabla
        JPanel panelTabla = new JPanel(new BorderLayout());
        
        //panel de botones
        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        buttonPanel.setBorder(new EmptyBorder(0, 0, 40, 0));
        card.add(buttonPanel, BorderLayout.SOUTH);
        buttonPanel.setBackground(Styles.bgLight);
        
        Button btn = new Button("Action");
        
    
    }


        
        private void setupLoginPanel(){

                /*LOGO LOGIN*/

            JLabel lblLogo = new JLabel("HECTOR");
            lblLogo.setBounds(128, 190, 250, 70); 
            lblLogo.setHorizontalAlignment(SwingConstants.CENTER);
            jLayeredPane2.add(lblLogo, JLayeredPane.PALETTE_LAYER);
            lblLogo.setFont(Styles.customFontXl);
            lblLogo.setForeground(Styles.fontLight);

            JLabel lblLogo2 = new JLabel("YAGUSZ");
            lblLogo2.setBounds(128, 235, 250, 70); 
            lblLogo2.setHorizontalAlignment(SwingConstants.CENTER);
            jLayeredPane2.add(lblLogo2, JLayeredPane.PALETTE_LAYER);
            lblLogo2.setFont(Styles.customFontXl);
            lblLogo2.setForeground(Styles.fontLight);

            JLabel lblLogo3 = new JLabel(" P   E   L   U   Q   U   E   R   I   A");
            lblLogo3.setBounds(128, 270, 250, 70); 
            lblLogo3.setHorizontalAlignment(SwingConstants.CENTER);
            jLayeredPane2.add(lblLogo3, JLayeredPane.PALETTE_LAYER);
            lblLogo3.setFont(Styles.customFontMd);
            lblLogo3.setForeground(Styles.fontLight);


            this.addComponentListener(new ComponentAdapter(){
                @Override
                public void componentResized(ComponentEvent e){
                    // Get the parent container's width and height
                    int parentWidth = jLayeredPane2.getWidth();
                    int parentHeight = jLayeredPane2.getHeight();

                    // Get each label's width and height
                    int lblLogoWidth = lblLogo.getWidth();
                    int lblLogoHeight = lblLogo.getHeight();

                    int lblLogo2Width = lblLogo2.getWidth();
                    int lblLogo2Height = lblLogo2.getHeight();

                    int lblLogo3Width = lblLogo3.getWidth();
                    int lblLogo3Height = lblLogo3.getHeight();

                    // Calculate new centered positions for each label
                    int lblLogoX = (parentWidth - lblLogoWidth) / 2;
                    int lblLogoY = (parentHeight - lblLogoHeight) / 2 - 30;

                    int lblLogo2X = (parentWidth - lblLogo2Width) / 2;
                    int lblLogo2Y = (parentHeight - lblLogo2Height) / 2 + 30;  // Adjust the y position if necessary

                    int lblLogo3X = (parentWidth - lblLogo3Width) / 2;
                    int lblLogo3Y = (parentHeight - lblLogo3Height) / 2 + 70;  // Adjust the y position if necessary

                    // Set the new bounds (x, y, width, height) for each label
                    lblLogo.setBounds(lblLogoX, lblLogoY, lblLogoWidth, lblLogoHeight);
                    lblLogo2.setBounds(lblLogo2X, lblLogo2Y, lblLogo2Width, lblLogo2Height);
                    lblLogo3.setBounds(lblLogo3X, lblLogo3Y, lblLogo3Width, lblLogo3Height);
                        }

                    }

                );
            
            jLayeredPane2.revalidate();
            jLayeredPane2.repaint();
            
        }
}